#!/usr/bin/env python3
"""Generate case-studies/CATALOG.md from case metadata tables.

The catalog is the single source of truth for case titles, difficulty,
and lecture mapping. Scans case-studies/student/*.md, reads each case's
metadata table, and regenerates CATALOG.md deterministically.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

FIELDS = ("id", "difficulty", "topics", "lecture")


def student_dir() -> Path:
    return ROOT / "case-studies" / "student"


def parse_metadata(text: str) -> dict:
    meta = {}
    in_meta = False
    for line in text.splitlines():
        if line.strip() == "| Field | Value |":
            in_meta = True
            continue
        if in_meta:
            if line.strip().startswith("|"):
                m = re.match(r"\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|", line)
                if m and m.group(1) != "Field":
                    meta[m.group(1).strip().lower()] = m.group(2).strip()
            else:
                break
    return meta


def title_of(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def main() -> int:
    student = student_dir()
    if not student.exists():
        print("case-studies/student/ missing", file=sys.stderr)
        return 1
    cases = []
    for f in sorted(student.glob("cs-*.md")):
        text = f.read_text(encoding="utf-8")
        meta = parse_metadata(text)
        missing = [k for k in FIELDS if k not in meta]
        if missing:
            print(f"{f.name}: missing metadata fields: {', '.join(missing)}", file=sys.stderr)
            return 1
        cases.append(
            {
                "id": meta["id"],
                "title": title_of(text),
                "difficulty": meta["difficulty"],
                "topics": meta["topics"],
                "lecture": meta["lecture"],
                "file": f.name,
            }
        )

    by_id = {}
    for c in cases:
        if c["id"] in by_id:
            print(f"Duplicate case id {c['id']} ({c['file']}, {by_id[c['id']]['file']})", file=sys.stderr)
            return 1
        by_id[c["id"]] = c

    cases.sort(key=lambda c: c["id"])
    lines = [
        "# Case-Study Catalog",
        "",
        "Auto-generated by `scripts/generate_catalog.py`. Do not edit by hand;",
        "edit the case files' metadata tables instead.",
        "",
        f"**{len(cases)} cases** · Difficulty levels: Beginner, Foundational, Intermediate, Advanced, Expert.",
        "",
        "| ID | Title | Difficulty | Lecture | Topics |",
        "| --- | --- | --- | --- | --- |",
    ]
    for c in cases:
        # lecture comes from the case's own metadata (cs-129+ are applied
        # additions mapped to existing lectures, so ID arithmetic is wrong)
        m = re.fullmatch(r"lecture-(\d{2})", c["lecture"])
        if not m:
            print(f"{c['id']}: bad lecture reference {c['lecture']!r}", file=sys.stderr)
            return 1
        lecture_num = int(m.group(1))
        link = f"[{c['title']}](student/{c['file']})"
        lines.append(
            f"| {c['id']} | {link} | {c['difficulty']} | [Lecture {lecture_num:02d}](../lectures/lecture-{lecture_num:02d}/plan.md) | {c['topics']} |"
        )
    lines.append("")
    (ROOT / "case-studies" / "CATALOG.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"CATALOG.md regenerated with {len(cases)} cases.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
